// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StaffApi.Models;

#nullable disable

namespace StaffApi.Migrations
{
    [DbContext(typeof(GestionContext))]
    [Migration("20230327182050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("StaffApi.Models.Employer", b =>
                {
                    b.Property<int>("EmployerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cantine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Caps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ostie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poste")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salaire")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Transport")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployerID");

                    b.ToTable("Employers");
                });
#pragma warning restore 612, 618
        }
    }
}
